### ISSUE TITLE
Without Passphrase

### ISSUE THREAD

**Issue by PapierFliegr** [enielrodriguez/conservation-mode-switcher#15]
Hello,

is it somehow possible to use the switch without using the passphrase?

For example the [Gnome-equivalent](https://github.com/laurento/gnome-shell-extension-ideapad) is able to do it without a passphrase.
As far as I know, the gnome-equiv uses `sudo` instead of `pkexec`, thus one can add the specific command, which switches the mode, to `sudoers`.

**Comment by enielrodriguez** [comment]
Hello! Yes, of course, I will do it as soon as I can. Thanks for the
feedback!

**Comment by PapierFliegr** [comment]
Works like a charm. Thank you :)

But I don't think it's a good idea to require "sudo tee" to be run without password.
I think that is too insecure, especially if one just wants to run this plasmoid without password.

To just use this specific command without password, I added
`%wheel ALL=(ALL) NOPASSWD: /usr/bin/tee <conservationmode-file>` to `/etc/sudoers.d/ideapad`.

As this depends on the conservationmode-file (and mine e.g. has characters to escape in its path), maybe you could add a line here, that prints out the command like 
```echo "%sudo ALL=(ALL) NOPASSWD: /usr/bin/tee /sys/bus/platform/drivers/ideapad_acpi/VPC????\:??/conservation_mode" | sudo tee /etc/sudoers.d/ideapad``` 
or with `%wheel` instead of `%sudo` if on Fedora or Arch (Code from [here](https://github.com/laurento/gnome-shell-extension-ideapad))
![image](https://github.com/enielrodriguez/lenovo-conservation-mode-switcher/assets/96027888/09b33711-929b-4220-9b07-583b23c2c546)

So the idea is that one just has to paste the command in the terminal and then uncheck the box.
As a note you could add then: To run without password, run `<command>` in terminal and uncheck box.

**Comment by enielrodriguez** [comment]
It's done!  
Thank you very much for your collaboration and sorry for the delay.

![Screenshot_20231231_125452](https://github.com/enielrodriguez/lenovo-conservation-mode-switcher/assets/31964610/f0cdb347-8483-4c15-8b11-03aa7fbe60dc)

**Comment by PapierFliegr** [comment]
Thank you, looks good :)
But the command in the tip won't work, since `:` (among others) is a special character and must be escaped with `\` in the `sudoers` file. See [here](https://access.redhat.com/solutions/3405281).

Probably fixable with something like [replace](https://doc.qt.io/qt-6/qstring.html#replace-11) and a regex expression.
