### ISSUE TITLE
"The conservation mode is not available" after update

### ISSUE THREAD

**Issue by roghed** [enielrodriguez/conservation-mode-switcher#18]
After updating to the new 1.2.2 (from 1.1) the widget works fine just after adding it to the taskbar, but after logging out and logging in it shows "conservation mode unavailable", same after restarting the system, therefore the only way to make it work is to remove it from the taskbar and add it again after every log-in.
The widget worked fine before the update.

**Comment by roghed** [comment]
I have updated to 1.2.3 and it seems that the issue is still there, but right now instead of showing the "Conservation mode unavailable" message it says "Conservation Mode is OFF." and there is an infinite spinning cogwheel.
![conservation_mode](https://github.com/enielrodriguez/lenovo-conservation-mode-switcher/assets/25582773/8b259499-868e-495e-8408-12506f90c091)
As before, removing and adding the widget fixes it temporarily until the next log-out/reboot.

**Comment by enielrodriguez** [comment]
Hello! Thank you very much for keeping me aware of these errors.
For some reason these errors are not easy to detect with plasmoidviewer.
I already released another version with a correction and other improvements that I was forced to make (hence the delay).

**Comment by roghed** [comment]
No worries, I've updated to 1.3.0 and it works great now. Btw, great widget, it's so much more convenient than switching the conservation mode through commandline. Keep up the good work 🙂
