### ISSUE TITLE
Plasma 6 support

### ISSUE THREAD

**Issue by mi16087** [enielrodriguez/conservation-mode-switcher#20]
After updating to KDE Plasma 6, this widget became unsuported:
![wid](https://github.com/enielrodriguez/lenovo-conservation-mode-switcher/assets/44554049/aaedc319-0932-4a69-a379-544e90051f6f)

**Comment by enielrodriguez** [comment]
Hello! There is already a version for KDE 6. Uninstall the current one and search the software center again. If you can't find it, check the readme.

**Comment by mi16087** [comment]
It doesn't seems to work, if i click on the icon in the panel it doesn't do anything, there is no popup or menu to switch conservation mode on and off, just the icon in the panel thet does nothing.

**Comment by lorisilbagnino** [comment]
I got the widget working by inserting it directly into the bar, **after** the system tray and not **inside** the system tray itself.
